name: heroicons_flutter
description: Heroicons set for Flutter available as IconData, great for UI development.
version: 1.0.0
homepage: https://github.com/pblinux/heroicons_flutter
repository: https://github.com/pblinux/heroicons_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: HeroIconsOutline
      fonts:
        - asset: lib/fonts/outline.ttf
    - family: HeroIconsSolid
      fonts:
        - asset: lib/fonts/solid.ttf
